#
# Hardware settings for HP ProBook 650 G1 15.6" Laptop
# Dual boot active. Windows @ sda4 / NixOS @ sda5
#
# flake.nix
#  └─ ./hosts
#      └─ ./laptop
#          ├─ default.nix
#          └─ hardware-configuration.nix *
#
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#

{ config, lib, pkgs, modulesPath, host, ... }:

{
   imports =
      [ (modulesPath + "/installer/scan/not-detected.nix")
      ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usbhid" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e88d78aa-b5cc-451e-9fd6-c1d07f28c884";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-af764af7-bb34-42d3-b374-de472c168a27".device = "/dev/disk/by-uuid/af764af7-bb34-42d3-b374-de472c168a27";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1E60-6F1B";
      fsType = "vfat";
    };

  swapDevices = [  ];

  networking = with host; {
    useDHCP = false;                        # Deprecated
    hostName = hostName;
    networkmanager.enable = true;
    interfaces = {
      enp0s31f6 = {
        useDHCP = true;                     # For versatility sake, manually edit IP on nm-applet.
        #ipv4.addresses = [ {
        #    address = "192.168.0.51";
        #    prefixLength = 24;
        #} ];
      };
      wlp0s20f3 = {
        useDHCP = true;
        #ipv4.addresses = [ {
        #  address = "192.168.0.51";
        #  prefixLength = 24;
        #} ];
      };
    };
#    defaultGateway = "192.168.0.1";
#    nameservers = [ "192.168.0.4" ];
    firewall = {
      enable = false;
      allowedUDPPorts = [ 500 4500 3389 5900 ];
      allowedTCPPorts = [ 500 4500 3389 5900 ];
    };
  };
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
